project_id: "554141"
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  # JSON 翻译文件
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /src/pages/**/*.mdx
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
